build:
  maxIssues: 50

config:
  validation: true

processors:
  active: true

console-reports:
  active: true

output-reports:
  active: true

style:
  active: true
  MagicNumber:
    active: true
    ignoreNumbers: ["-1", "0", "1", "2"]
  WildcardImport:
    active: true
  NewLineAtEndOfFile:
    active: true
  MaxLineLength:
    active: true
    maxLineLength: 120
    excludePackageStatements: true
    excludeImportStatements: true
    excludeCommentStatements: true

complexity:
  active: true
  NestedBlockDepth:
    active: true
    threshold: 6
    ignoreAnnotated:
      - "Composable"
  LongParameterList:
    active: true
    functionThreshold: 8
    constructorThreshold: 8
    ignoreDefaultParameters: true
  CyclomaticComplexMethod:
    active: true
    threshold: 15
    ignoreAnnotated:
      - "Composable"
  CognitiveComplexMethod:
    active: true
    threshold: 15
    ignoreAnnotated:
      - "Composable"
  LongMethod:
    active: true
    threshold: 120
    ignoreAnnotated:
      - "Composable"
